[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.62.2"
  HUGO_ENABLEGITINFO = "true"
  
[context.branch-deploy.environment]
  HUGO_VERSION = "0.62.2"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/shiny/*"
  to = "http://207.154.198.215/shiny/:splat/"
  status = 200
  force = true
