---
output:
  pdf_document:
    latex_engine: pdflatex
    template: ./template/svm-latex-cv.tex
geometry: margin=1in

title: ""
author: Kostas Vasilopoulos

jobtitle: Ph.D. Candidate Lancaster University
#address: "Guinness Brewery · Park Royal · London NW10 7RR, UK"
fontawesome: yes
email: k.vasilopoulos@lancaster.ac.uk
email2: k.vasilopoulo@gmail.com
github: kvasilopoulos
phone: "+44 (0) 7392971743"
web: kvasilopoulos.netlify.com
updated: no

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

# Research Interests

* Macroeconomics,   Real  Estate  Markets,   Time  Series Modeling, Credit Frictions, Dynamic Stochastic General Equilibrium (DSGE) modelling

# Education

* *Lancaster University*, Ph.D. Economics \hfill Oct 2016- Present

* *University of Macedonia, Greece*, Ms.C. Economics \hfill Sept 2014- March 2016

* *University of Macedonia, Greece*, Bs.C. Economics \hfill Sept 2009- Aug 2014

# Working Papers

* Vasilopoulos K., Tayler W. (2019). Commercial Real Estate, Housing and the Business Cycle.

* Vasilopoulos K., Pavlidis E. (2019). Speculative Bubbles in Segmented Markets: Evidence from Chinese Cross-Listed Stocks.


# Projects & Research Groups

* UK Housing Observatory [[link]](http://www.lancaster.ac.uk/lums/economics/research/housing/)

* International Housing Observatory [[link]](https://lancs-macro.shinyapps.io/international-housing-observatory/)

* Centre for Financial Econometrics, Asset Markets and Macroeconomic Policy

# IT Literacy

* R: Advanced knowledge 

* Python, Matlab, C++, Git, Latex: Intermediate Knowledge

* HTML/CSS: Basic knowledge

# Technical Publications

*   Vasilopoulos Kostas, Pavlidis Efthymios, Spavound Simon and Martínez-García Enríque (2019) exuber: Testing and Simulating Explosive Periods. R package version 0.3.0. https://CRAN.R-project.org/package=exuber

*   Vasilopoulos Kostas and Pavlidis Efthymios (2019) ivx: Robust Econometric Inference. R package version 1.0.0.9000. https://CRAN.R-project.org/package=ivx

# Conference Presentations

* 3rd Annual International Conference on Macroeconomic Analysis and International Finance, Rethymno, May, 2019

* North West Social Sciences Doctoral Training Partnership, Lancaster University, Lancaster, May, 2019

* 5th International Conference on Applied Theory, Macro and Empirical Finance,
University of Macedonia, Thessaloniki, April 2019

* The 12th International Conference on Computational and Financial Econometrics , University of Pisa, Pisa, 14-16 December 2018.

* 4th International Conference on Applied Theory, Macro and Empirical Finance, University of Macedonia, Thessaloniki, April, 2018

* North West Social Sciences Doctoral Training Partnership The University of Manchester, Manchester, May, 2018

* 3rd International Conference on Applied Theory, Macro and Empirical Finance, University of Macedonia, Thessaloniki, April, 2017

# Grants, Awards, and Fellowships

* Departmental Studentship Award, Lancaster University, 2016–2019

* Scholarship awarded based on academic excellence, University of Macedonia

# Teaching 

 * TA, Econ222: Intermediate Macroeconomics 
 
 * TA, Econ102: Principles of Economics B

# Summer Schools, Workshops and Training

* Summer School -  Advanced Courses on DSGE Macroeconomic Modelling, 4-8 Sept 2017, University of Surrey, UK. [[link]](https://www.surrey.ac.uk/events/20180903-foundations-and-advanced-courses-dsge-macroeconomic-modelling-and-conference-summer)

* 4th Short Course: Dynamic Programming – Theory, Computation and Empirical Applications 
July 04-08, 2016 Thessaloniki, Greece. [[link]](http://sce2016.uom.gr/)


# References

Available upon request, though likely would include Efthymios Pavlidis and William Tayler.