[build]
  command = "hugo --gc --minify -b $URL --themesDir ../../"
  base    = "exampleSite"
  publish = "exampleSite/public"

[build.environment]
  HUGO_THEME = "repo"
  HUGO_VERSION = "0.60.1"
  HUGO_ENABLEGITINFO = "true"
