---
output:
  pdf_document:
    latex_engine: pdflatex
    template: ./svm-template/svm-latex-cv.tex
geometry: margin=1in

title: "Curriculum Vitae"
subtitle: "<a href='cv.pdf' download='kostas-vasilopoulos-cv.pdf'> <i class='fa fa-download'></i> Download <br> </a>"
author: Kostas Vasilopoulos
widget: "cv"

jobtitle: "Teaching Associate Lancaster University"
address: 
fontawesome: yes
email: k.vasilopoulos@lancaster.ac.uk
email2: k.vasilopoulo@gmail.com
github: kvasilopoulos
# linkedin: kostas-vasilopoulos-130718128/
phone: "+44 (0) 7392971743"
web: kvasilopoulos.com
updated: no
keywords: R Markdown, academic CV, template

# fontfamily: mathpazo
# fontfamilyoptions: sc, osf
fontsize: 10pt
linkcolor: blue
urlcolor: blue
---

# Research Interests 

Macroeconomics, Real Estate Markets, Time  Series Modeling, Credit Frictions, Dynamic Stochastic General Equilibrium (DSGE) modelling

<!--- Employment --->

# Employment

 **Teaching Associate** \hfill <span style = "float:right;">  *Nov 2020 - * </span> \newline <br>
  Lancaster University  \hfill <span style = "float:right;"> *Lancaster, UK* </span>

 **Research Assistant, UK Housing Observatory** \hfill <span style = "float:right;">  *Mar 2019 - Sep 2020* </span> \newline <br>
  Lancaster University  \hfill <span style = "float:right;"> *Lancaster, UK* </span>

  **Graduate Teaching Assistant** \hfill <span style = "float:right;">  *Oct 2016 - Sep 2020* </span> \newline <br>
  Lancaster University  \hfill <span style = "float:right;"> *Lancaster, UK* </span>


<!--- Education --->

# Education 

\vspace{2mm}

  **Ph.D. Economics** \hfill <span style = "float:right;">  *Oct 2016 - Nov 2020* </span> \newline <br>
  Lancaster University  \hfill <span style = "float:right;"> *Lancaster, UK* </span>

  **M.Sc. Economics**  \hfill  <span style = "float:right;"> *Sept 2014 - March 2016* </span> \newline <br>
  University of Macedonia  \hfill <span style = "float:right;"> *Thessaloniki, Greece* </span>

  **B.Sc. Economics**  \hfill  <span style = "float:right;"> *Sept 2009 - Aug 2014* </span> \newline <br>
  University of Macedonia \hfill <span style = "float:right;"> *Thessaloniki, Greece* </span>


<!--- Research --->

# Research


## Publications

* Pavlidis E., Vasilopoulos K. (2020). Speculative Bubbles in Segmented Markets: Evidence from Chinese Cross-Listed Stocks. **Journal of International Money and Finance** .

## Submitted

* Vasilopoulos K., Pavlidis E., Martínez-García E.(2020). exuber: Recursive Right-Tailed Unit Root Testing with R. **Dallas Fed Working Paper**.

* Vasilopoulos K., Tayler W. (2020). Real Estate and Construction Sector Dynamics in the Business Cycle. **Working Paper**

## Work in Progress

* Pavlidis E., Vasilopoulos K. (2020). Sentimental Housing Markets. 

* Vasilopoulos K. (2020). Real Estate and Monetary Policy: Residential and Commercial.

* Skouralis A., Vasilopoulos K. (2020). Asymmetries Effects of Housing Demand Shocks.

<!--- Projects --->

# Projects & Research Groups

<!-- I am a member and the maintainer of two projects on monitoring housing markets for episodes of exuberance: -->

* UK Housing Observatory - Lancaster  University \newline <br> 
Website: [uk.housing-observatory.com](uk.housing-observatory.com) 

* International Housing Observatory - Lancaster University and the Globalization and Monetary Policy Institute of the Federal Reserve Bank of Dallas \newline <br>
Website : [int.housing-observatory.com](int.housing-observatory.com) 
    

<!--- Teaching --->

# Teaching 

Teaching Associate:

 * Econ223: Intermediate Macroeconomics II (UG), Spring, 2021
 
 * Econ 324: Advanced Macroeconomics (UG), Spring 2021
 
 * Econ 400: Macroeconomics for Money, Banking and Finance (UG), Fall 2020
 
 * Econ 101: Principles of Economics A (UG), 2020-2021

Graduate Teaching Assistant:

 * Econ222: Intermediate Macroeconomics (UG), Fall 2018, Fall 2019
 
 * Econ102: Principles of Economics B (UG), 2016-2017, 2017-2018
 
 

<!--- Technical Publications --->

# Technical Publications

*   Vasilopoulos Kostas, Pavlidis Efthymios, Spavound Simon and Martínez-García Enríque (2019) exuber: Testing and Simulating Explosive Periods. R package version 0.3.1. https://CRAN.R-project.org/package=exuber

*   Vasilopoulos Kostas and Pavlidis Efthymios (2019) ivx: Robust Econometric Inference. R package version 1.1.0. https://CRAN.R-project.org/package=ivx

 
# Grants, Awards, and Fellowships

* Departmental Studentship Award, Lancaster University, 2016–2019

* Scholarship awarded based on academic excellence, University of Macedonia

<!--- Conferences --->

# Conference Presentations

```{r confs, echo=FALSE, results='asis'}
conferences_md <- here::here("content/events/conferences.md")
cat(paste0(readLines(conferences_md)[-c(1:17)], collapse = "\n"))
```

<!-- ## 2019 -->

<!--   * Lancaster PhD Summer School on Applied Macroeconometrics, Lancaster, September, 2019 -->

<!--   * 3rd Annual International Conference on Macroeconomic Analysis and International Finance, Rethymno, May, 2019 -->

<!--   * North West Social Sciences Doctoral Training Partnership, Lancaster University, Lancaster, May, 2019 -->

<!--   * 5th International Conference on Applied Theory, Macro and Empirical Finance, -->
<!-- University of Macedonia, Thessaloniki, April 2019 -->

<!-- ## 2018 -->

<!--   * The 12th International Conference on Computational and Financial Econometrics , University of Pisa, Pisa, 14-16 December 2018. -->

<!--   * 4th International Conference on Applied Theory, Macro and Empirical Finance, University of Macedonia, Thessaloniki, April, 2018 -->

<!--   * North West Social Sciences Doctoral Training Partnership The University of Manchester, Manchester, May, 2018 -->

<!-- ## 2017 -->

<!--   * 3rd International Conference on Applied Theory, Macro and Empirical Finance, University of Macedonia, Thessaloniki, April, 2017 -->


# Teaching Courses

* Graduate Teaching Assistants Workshop, University of Nottingham, Oct 2016

* Introduction to Teaching at Lancaster (ITL), Lancaster University, Oct 2016


<!--- Events --->

# Summer Schools, Workshops and Training

* Summer School - Bayesian Methods for Empirical Macroeconomics, 29th – 30th June 2020, Lancaster University, UK.
[[link]](https://sites.google.com/view/lancseconsummer/home)

* Summer School - Applied Macroeconometrics, 25th – 27th September 2019, Lancaster University, UK.
[[link]](http://wp.lancs.ac.uk/lancaster-phd-summer-school-2019/)

* Summer School -  Advanced Courses on DSGE Macroeconomic Modelling, 4-8 Sept 2017, University of Surrey, UK. [[link]](https://www.surrey.ac.uk/events/20180903-foundations-and-advanced-courses-dsge-macroeconomic-modelling-and-conference-summer)

* 4th Short Course: Dynamic Programming – Theory, Computation and Empirical Applications 
July 04-08, 2016 Thessaloniki, Greece. [[link]](http://sce2016.uom.gr/)

<!--- IT Literacy --->

# IT Literacy

Advanced knowledge:  R, Matlab

Intermediate Knowledge: Python, C++, Git, Latex

Basic knowledge: HTML/CSS



<!--- References --->

# References

**Efthymios Pavlidis** \newline <br>
Professor in Economics \newline <br>
Lancaster University \newline <br>
E-mail: [e.pavlidis@lancaster.ac.uk](e.pavlidis@lancaster.ac.uk) \newline <br>
URL: [https://sites.google.com/site/etpavlidis/](https://sites.google.com/site/etpavlidis/)

**William Tayler** \newline <br>
Lecturer (Assistant Professor) in Economics \newline <br>
Lancaster University \newline <br>
E-mail: [w.tayler@lancaster.ac.uk](w.tayler@lancaster.ac.uk) \newline <br>
URL: [https://sites.google.com/site/williamjtayler/](https://sites.google.com/site/williamjtayler/)   

**Ivan Paya** \newline <br>
Professor in Economics \newline <br>
Lancaster University \newline <br>
E-mail: [i.paya@lancaster.ac.uk](i.paya@lancaster.ac.uk) \newline <br>
URL: [https://ivanpaya.weebly.com/](https://ivanpaya.weebly.com/) 